_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/optimizer_270e.yml',
  '_base_/yolov3_r34.yml',
  '_base_/yolov3_reader.yml',
]

snapshot_epoch: 1
weights: output/yolov3_r34_270e_coco/model_final
